# Generated by Django 5.0.1 on 2024-01-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_url', models.URLField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
